/* Generated by c-to-tzo */
// 0 "YEHAT_SHIP_MONTH" setContext
// 0 "YEHAT_SHIP_DAY" setContext
// 0 "YEHAT_SHIP_YEAR" setContext
// 0 "player_said" setContext
// 0 "YEHAT_REBEL_INFO" setContext
// 0 "YEHAT_ABSORBED_PKUNK" setContext
// 0 "YEHAT_REBEL_TOLD_PKUNK" setContext
// 0 "PKUNK_VISITS" setContext
// 0 "PKUNK_HOME_VISITS" setContext
// 0 "IN_LAST_BATTLE" setContext
// 0 "YEHAT_REBEL_VISITS" setContext
// "Intro" goto
// nop #peace
// "PEACE" emit exit
/*Copyright Paul Reiche, Fred Ford. 1992-2002 */

/*
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software // jgz
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "../commall.h"
#include "../yehat/resinst.h"
#include "strings.h"

#include "uqm/build.h"

static LOCDATA yehat_desc =
    {
        NULL,             /* init_encounter_func */
        NULL,             /* post_encounter_func */
        NULL,             /* uninit_encounter_func */
        YEHAT_PMAP_ANIM,  /* AlienFrame */
        YEHAT_FONT,       /* AlienFont */
        WHITE_COLOR_INIT, /* AlienTextFColor */
        BLACK_COLOR_INIT, /* AlienTextBColor */
        {0, 0},           /* AlienTextBaseline */
        0,
        /* (SIS_TEXT_WIDTH - 16) * 2 / 3, */ /* AlienTextWidth */
        ALIGN_CENTER,                        /* AlienTextAlign */
        VALIGN_MIDDLE,                       /* AlienTextValign */
        YEHAT_COLOR_MAP,                     /* AlienColorMap */
        YEHAT_MUSIC,                         /* AlienSong */
        NULL_RESOURCE,                       /* AlienAltSong */
        0,                                   /* AlienSongFlags */
        REBEL_CONVERSATION_PHRASES,          /* PlayerPhrases */
        15,                                  /* NumAnimations */
        {
            /* AlienAmbientArray (ambient animations) */
            {
                /* right hand-wing tapping keyboard; front guy */
                4,                        /* StartIndex */
                3,                        /* NumFrames */
                YOYO_ANIM | WAIT_TALKING, /* AnimFlags */
                ONE_SECOND / 10,
                ONE_SECOND / 10, /* FrameRate */
                ONE_SECOND,
                ONE_SECOND * 3, /* RestartRate */
                (1 << 6) | (1 << 7),
            },
            {
                /* left hand-wing tapping keyboard; front guy */
                7,                        /* StartIndex */
                3,                        /* NumFrames */
                YOYO_ANIM | WAIT_TALKING, /* AnimFlags */
                ONE_SECOND / 10,
                ONE_SECOND / 10, /* FrameRate */
                ONE_SECOND,
                ONE_SECOND * 3, /* RestartRate */
                (1 << 6) | (1 << 7),
            },
            {
                10,        /* StartIndex */
                3,         /* NumFrames */
                YOYO_ANIM, /* AnimFlags */
                ONE_SECOND / 20,
                0, /* FrameRate */
                ONE_SECOND,
                ONE_SECOND * 3, /* RestartRate */
                (1 << 4) | (1 << 14),
            },
            {
                13,        /* StartIndex */
                3,         /* NumFrames */
                YOYO_ANIM, /* AnimFlags */
                ONE_SECOND / 20,
                0, /* FrameRate */
                ONE_SECOND,
                ONE_SECOND * 3, /* RestartRate */
                (1 << 5),
            },
            {
                16,        /* StartIndex */
                5,         /* NumFrames */
                YOYO_ANIM, /* AnimFlags */
                ONE_SECOND / 15,
                ONE_SECOND / 15, /* FrameRate */
                ONE_SECOND * 10,
                ONE_SECOND * 3, /* RestartRate */
                (1 << 2) | (1 << 14),
            },
            {
                21,        /* StartIndex */
                5,         /* NumFrames */
                YOYO_ANIM, /* AnimFlags */
                ONE_SECOND / 15,
                ONE_SECOND / 15, /* FrameRate */
                ONE_SECOND * 10,
                ONE_SECOND * 3, /* RestartRate */
                (1 << 3),
            },
            {
                /* right arm-wing rising; front guy */
                26,                       /* StartIndex */
                2,                        /* NumFrames */
                YOYO_ANIM | WAIT_TALKING, /* AnimFlags */
                ONE_SECOND / 15,
                ONE_SECOND / 15, /* FrameRate */
                ONE_SECOND * 10,
                ONE_SECOND * 3, /* RestartRate */
                (1 << 0) | (1 << 1),
            },
            {
                /* left arm-wing rising; front guy */
                28,                       /* StartIndex */
                2,                        /* NumFrames */
                YOYO_ANIM | WAIT_TALKING, /* AnimFlags */
                ONE_SECOND / 15,
                ONE_SECOND / 15, /* FrameRate */
                ONE_SECOND * 10,
                ONE_SECOND * 3, /* RestartRate */
                (1 << 0) | (1 << 1),
            },
            {
                30,                               /* StartIndex */
                3,                                /* NumFrames */
                YOYO_ANIM,                        /* AnimFlags */
                ONE_SECOND / 30, ONE_SECOND / 30, /* FrameRate */
                ONE_SECOND / 30, ONE_SECOND / 30, /* RestartRate */
                0,                                /* BlockMask */
            },
            {
                33,                               /* StartIndex */
                3,                                /* NumFrames */
                YOYO_ANIM,                        /* AnimFlags */
                ONE_SECOND / 30, ONE_SECOND / 30, /* FrameRate */
                ONE_SECOND / 30, ONE_SECOND / 30, /* RestartRate */
                0,                                /* BlockMask */
            },
            {
                36,                               /* StartIndex */
                3,                                /* NumFrames */
                YOYO_ANIM,                        /* AnimFlags */
                ONE_SECOND / 30, ONE_SECOND / 30, /* FrameRate */
                ONE_SECOND / 30, ONE_SECOND / 30, /* RestartRate */
                0,                                /* BlockMask */
            },
            {
                39,                               /* StartIndex */
                3,                                /* NumFrames */
                YOYO_ANIM,                        /* AnimFlags */
                ONE_SECOND / 30, ONE_SECOND / 30, /* FrameRate */
                ONE_SECOND / 30, ONE_SECOND / 30, /* RestartRate */
                0,                                /* BlockMask */
            },
            {
                42,                               /* StartIndex */
                3,                                /* NumFrames */
                YOYO_ANIM,                        /* AnimFlags */
                ONE_SECOND / 30, ONE_SECOND / 30, /* FrameRate */
                ONE_SECOND / 30, ONE_SECOND / 30, /* RestartRate */
                0,                                /* BlockMask */
            },
            {
                45,                               /* StartIndex */
                3,                                /* NumFrames */
                YOYO_ANIM,                        /* AnimFlags */
                ONE_SECOND / 30, ONE_SECOND / 30, /* FrameRate */
                ONE_SECOND / 30, ONE_SECOND / 30, /* RestartRate */
                0,                                /* BlockMask */
            },
            {
                48,                       /* StartIndex */
                4,                        /* NumFrames */
                YOYO_ANIM | WAIT_TALKING, /* AnimFlags */
                ONE_SECOND / 30,
                0, /* FrameRate */
                ONE_SECOND,
                ONE_SECOND * 3, /* RestartRate */
                (1 << 2) | (1 << 4),
            },
        },
        {
            /* AlienTransitionDesc - empty */
            0,    /* StartIndex */
            0,    /* NumFrames */
            0,    /* AnimFlags */
            0, 0, /* FrameRate */
            0, 0, /* RestartRate */
            0,    /* BlockMask */
        },
        {
            /* AlienTalkDesc */
            1,                  /* StartIndex */
            3,                  /* NumFrames */
            0,                  /* AnimFlags */
            ONE_SECOND / 15, 0, /* FrameRate */
            ONE_SECOND / 12, 0, /* RestartRate */
            0,                  /* BlockMask */
        },
        NULL, /* AlienNumberSpeech - none */
        /* Filler for loaded resources */
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
};

static void
PrepareShip(void)
{
    BYTE mi, di, yi;

    mi = (GLOBAL(GameClock.month_index) % 12) + 1;
    SET_GAME_STATE(YEHAT_SHIP_MONTH, mi);        // 0 "YEHAT_SHIP_MONTH" setContext
    if ((di = GLOBAL(GameClock.day_index)) > 28) // jgz
    {                                            // {
        di = 28;
    }                                   // }
    SET_GAME_STATE(YEHAT_SHIP_DAY, di); // 0 "YEHAT_SHIP_DAY" setContext
    yi = (BYTE)(GLOBAL(GameClock.year_index) - START_YEAR);
    if (mi == 1) // jgz
    {            // {
        ++yi;
    }                                    // }
    SET_GAME_STATE(YEHAT_SHIP_YEAR, yi); // 0 "YEHAT_SHIP_YEAR" setContext
} // getResponse goto exit }

static void
ExitConversation(RESPONSE_REF R) // { nop #ExitConversation
{
    if (PLAYER_SAID(R, bye_rebel)) // "player_said" getContext "bye_rebel" eq jgz
    {                              // {
        NPCPhrase(GOODBYE_REBEL);  // "GOODBYE_REBEL" emit
    }                              // }
} // getResponse goto exit }

static void Rebels(RESPONSE_REF R);

static void
RebelInfo(RESPONSE_REF R) // { nop #RebelInfo
{
    BYTE InfoLeft;

    InfoLeft = FALSE;                           // 0 "_info_left" setContext
    if (PLAYER_SAID(R, give_info_rebels))       // "player_said" getContext "give_info_rebels" eq jgz
    {                                           // {
        NPCPhrase(WHAT_INFO);                   // "WHAT_INFO" emit
    }                                           // }
    else if (PLAYER_SAID(R, what_about_urquan)) // "player_said" getContext "what_about_urquan" eq jgz
    {                                           // {
        NPCPhrase(ABOUT_URQUAN);                // "ABOUT_URQUAN" emit

        DISABLE_PHRASE(what_about_urquan);       // "what_about_urquan" disableOption
    }                                            // }
    else if (PLAYER_SAID(R, what_about_royalty)) // "player_said" getContext "what_about_royalty" eq jgz
    {                                            // {
        NPCPhrase(ABOUT_ROYALTY);                // "ABOUT_ROYALTY" emit

        DISABLE_PHRASE(what_about_royalty);  // "what_about_royalty" disableOption
    }                                        // }
    else if (PLAYER_SAID(R, what_about_war)) // "player_said" getContext "what_about_war" eq jgz
    {                                        // {
        NPCPhrase(ABOUT_WAR);                // "ABOUT_WAR" emit

        DISABLE_PHRASE(what_about_war);      // "what_about_war" disableOption
    }                                        // }
    else if (PLAYER_SAID(R, what_about_vux)) // "player_said" getContext "what_about_vux" eq jgz
    {                                        // {
        NPCPhrase(ABOUT_VUX);                // "ABOUT_VUX" emit

        DISABLE_PHRASE(what_about_vux);       // "what_about_vux" disableOption
    }                                         // }
    else if (PLAYER_SAID(R, what_about_clue)) // "player_said" getContext "what_about_clue" eq jgz
    {                                         // {
        NPCPhrase(ABOUT_CLUE);                // "ABOUT_CLUE" emit

        DISABLE_PHRASE(what_about_clue); // "what_about_clue" disableOption
    }                                    // }

    if (PHRASE_ENABLED(what_about_urquan))       // "what_about_urquan" optionEnabled 1 eq jgz
    {                                            // {
        Response(what_about_urquan, RebelInfo);  // "what_about_urquan" ppc 4 + { "what_about_urquan" "player_said" setContext "RebelInfo" goto } response
        InfoLeft = TRUE;                         // 1 "_info_left" setContext
    }                                            // }
    if (PHRASE_ENABLED(what_about_royalty))      // "what_about_royalty" optionEnabled 1 eq jgz
    {                                            // {
        Response(what_about_royalty, RebelInfo); // "what_about_royalty" ppc 4 + { "what_about_royalty" "player_said" setContext "RebelInfo" goto } response
        InfoLeft = TRUE;                         // 1 "_info_left" setContext
    }                                            // }
    if (PHRASE_ENABLED(what_about_war))          // "what_about_war" optionEnabled 1 eq jgz
    {                                            // {
        Response(what_about_war, RebelInfo);     // "what_about_war" ppc 4 + { "what_about_war" "player_said" setContext "RebelInfo" goto } response
        InfoLeft = TRUE;                         // 1 "_info_left" setContext
    }                                            // }
    if (PHRASE_ENABLED(what_about_vux))          // "what_about_vux" optionEnabled 1 eq jgz
    {                                            // {
        Response(what_about_vux, RebelInfo);     // "what_about_vux" ppc 4 + { "what_about_vux" "player_said" setContext "RebelInfo" goto } response
        InfoLeft = TRUE;                         // 1 "_info_left" setContext
    }                                            // }
    if (PHRASE_ENABLED(what_about_clue))         // "what_about_clue" optionEnabled 1 eq jgz
    {                                            // {
        Response(what_about_clue, RebelInfo);    // "what_about_clue" ppc 4 + { "what_about_clue" "player_said" setContext "RebelInfo" goto } response
        InfoLeft = TRUE;                         // 1 "_info_left" setContext
    }                                            // }
    Response(enough_info, Rebels);               // "enough_info" ppc 4 + { "enough_info" "player_said" setContext "Rebels" goto } response

    if (!InfoLeft)                        // "_info_left" getContext not jgz
    {                                     // {
        DISABLE_PHRASE(give_info_rebels); // "give_info_rebels" disableOption
    }                                     // }
} // getResponse goto exit }

static void
Rebels(RESPONSE_REF R) // { nop #Rebels
{
    SBYTE NumVisits;

    if (PLAYER_SAID(R, how_goes_revolution))          // "player_said" getContext "how_goes_revolution" eq jgz
    {                                                 // {
        NumVisits = GET_GAME_STATE(YEHAT_REBEL_INFO); // "YEHAT_REBEL_INFO" getContext
        switch (NumVisits++)
        {
        case 0:                            // dup 0 eq jgz {
            NPCPhrase(REBEL_REVOLUTION_1); // "REBEL_REVOLUTION_1" emit "YEHAT_REBEL_INFO" getContext 1 + "YEHAT_REBEL_INFO" setContext
            break;                         // }
        case 1:                            // dup 1 eq jgz {
            NPCPhrase(REBEL_REVOLUTION_2); // "REBEL_REVOLUTION_2" emit "YEHAT_REBEL_INFO" getContext 1 + "YEHAT_REBEL_INFO" setContext
            break;                         // }
        case 2:                            // dup 2 eq jgz {
            NPCPhrase(REBEL_REVOLUTION_3); // "REBEL_REVOLUTION_3" emit "YEHAT_REBEL_INFO" getContext 1 + "YEHAT_REBEL_INFO" setContext
            break;                         // }
        case 3:                            // 3 eq jgz {
            NPCPhrase(REBEL_REVOLUTION_4); // "REBEL_REVOLUTION_4" emit
            --NumVisits;
            break; // }
        }
        SET_GAME_STATE(YEHAT_REBEL_INFO, NumVisits); //

        DISABLE_PHRASE(how_goes_revolution);                                                                               // "how_goes_revolution" disableOption
    }                                                                                                                      // }
    else if (PLAYER_SAID(R, any_ships))                                                                                    // "player_said" getContext "any_ships" eq jgz
    { /* TODO: fix this entire section! */                                                                                 // {
        if (GET_GAME_STATE(YEHAT_SHIP_MONTH)                                                                               // "YEHAT_SHIP_MONTH" getContext 0 eq
            && ((NumVisits = (GLOBAL(GameClock.year_index) - START_YEAR) - GET_GAME_STATE(YEHAT_SHIP_YEAR)) < 0            // "YEHAT_SHIP_YEAR" getContext 0 eq and
                || ((NumVisits == 0 && (NumVisits = GLOBAL(GameClock.month_index) - GET_GAME_STATE(YEHAT_SHIP_MONTH)) < 0) // "YEHAT_SHIP_MONTH" getContext 0 eq and
                    || (NumVisits == 0 && GLOBAL(GameClock.day_index) < GET_GAME_STATE(YEHAT_SHIP_DAY)))))                 // "YEHAT_SHIP_DAY" getContext 0 eq and jgz
        {                                                                                                                  // {
            NPCPhrase(NO_SHIPS_YET);                                                                                       // "NO_SHIPS_YET" emit
        }                                                                                                                  // }
        else if ((NumVisits = EscortFeasibilityStudy(YEHAT_SHIP)) == 0) /* ???? how to implement? */                       // 0 jgz
        {                                                                                                                  // {
            NPCPhrase(NO_ROOM);                                                                                            // "NO_ROOM" emit
        }                                                                                                                  // }
        else                                                                                                               //
        {                                                                                                                  // {
#define NUM_YEHAT_SHIPS 4                                                                                                  //
            if (NumVisits < NUM_YEHAT_SHIPS)                                                                               // 0 jgz
            {                                                                                                              // {
                NPCPhrase(HAVE_FEW_SHIPS);                                                                                 // "HAVE_FEW_SHIPS" emit
            }                                                                                                              // }
            else                                                                                                           // 0 jz
            {                                                                                                              // {
                NumVisits = NUM_YEHAT_SHIPS;                                                                               //
                NPCPhrase(HAVE_ALL_SHIPS);                                                                                 // "HAVE_ALL_SHIPS" emit
            }                                                                                                              // }
                                                                                                                           //
            AlienTalkSegue((COUNT)~0);                                                                                     //
            AddEscortShips(YEHAT_SHIP, NumVisits);                                                                         //
            PrepareShip();                                                                                                 //
        }                                                                                                                  // }
                                                                                                                           //
        DISABLE_PHRASE(any_ships);                                                                                         // "any_ships" disableOption
    }                                                                                                                      // }
    else if (PLAYER_SAID(R, what_about_pkunk_rebel))                                                                       // "player_said" getContext "what_about_pkunk_rebel" eq jgz
    {                                                                                                                      // {
        if (GET_GAME_STATE(YEHAT_ABSORBED_PKUNK))                                                                          // "YEHAT_ABSORBED_PKUNK" getContext jgz
        {                                                                                                                  // {
            NPCPhrase(PKUNK_ABSORBED_REBEL);                                                                               // "PKUNK_ABSORBED_REBEL" emit
        }                                                                                                                  // }
        else
        {                                // {
            NPCPhrase(HATE_PKUNK_REBEL); // "HATE_PKUNK_REBEL" emit
        }                                // }

        SET_GAME_STATE(YEHAT_REBEL_TOLD_PKUNK, 1); // 1 "YEHAT_REBEL_TOLD_PKUNK" setContext
    }                                              // }
    else if (PLAYER_SAID(R, enough_info))          // "player_said" getContext "enough_info" eq jgz
    {                                              // {
        NPCPhrase(OK_ENOUGH_INFO);                 // "OK_ENOUGH_INFO" emit
    }                                              // }

    if (PHRASE_ENABLED(how_goes_revolution))      // "how_goes_revolution" optionEnabled 1 eq jgz
    {                                             // {
        Response(how_goes_revolution, Rebels);    // "how_goes_revolution" ppc 4 + { "how_goes_revolution" "player_said" setContext "Rebels" goto } response
    }                                             // }
    if (!GET_GAME_STATE(YEHAT_REBEL_TOLD_PKUNK)   // "YEHAT_REBEL_TOLD_PKUNK" getContext not
        && GET_GAME_STATE(PKUNK_VISITS)           // "PKUNK_VISITS" getContext and
        && GET_GAME_STATE(PKUNK_HOME_VISITS))     // "PKUNK_HOME_VISITS" getContext and jgz
    {                                             // {
        Response(what_about_pkunk_rebel, Rebels); // "what_about_pkunk_rebel" ppc 4 + { "what_about_pkunk_rebel" "player_said" setContext "Rebels" goto } response
    }                                             // }
    if (PHRASE_ENABLED(any_ships))                // "any_ships" optionEnabled 1 eq jgz
    {                                             // {
        Response(any_ships, Rebels);              // "any_ships" ppc 4 + { "any_ships" "player_said" setContext "Rebels" goto } response
    }                                             // }
    if (PHRASE_ENABLED(give_info_rebels))         // "give_info_rebels" optionEnabled 1 eq jgz
    {                                             // {
        Response(give_info_rebels, RebelInfo);    // "give_info_rebels" ppc 4 + { "give_info_rebels" "player_said" setContext "RebelInfo" goto } response
    }                                             // }
    Response(bye_rebel, ExitConversation);        // "bye_rebel" ppc 4 + { "bye_rebel" "player_said" setContext "ExitConversation" goto } response
} // getResponse goto exit }

static void
Intro(void) // { nop #Intro
{
    BYTE NumVisits;

    setSegue(Segue_peace);
    if (LOBYTE(GLOBAL(CurrentActivity)) == IN_LAST_BATTLE) // "IN_LAST_BATTLE" getContext dup jgz
    {                                                      // {
        NPCPhrase(YEHAT_CAVALRY);                          // "YEHAT_CAVALRY" emit
        AlienTalkSegue((COUNT)~0);

        NumVisits = (BYTE)EscortFeasibilityStudy(YEHAT_REBEL_SHIP);
        if (NumVisits > 8) // jgz
        {                  // {
            NumVisits = 8;
        } // }
        AddEscortShips(YEHAT_REBEL_SHIP, NumVisits - (NumVisits >> 1));
        AddEscortShips(PKUNK_SHIP, NumVisits >> 1);
    }                                                   // }
    else                                                // jz
    {                                                   // {
        NumVisits = GET_GAME_STATE(YEHAT_REBEL_VISITS); // "YEHAT_REBEL_VISITS" getContext
        switch (NumVisits++)
        {
        case 0:                       // dup 0 eq jgz {
            NPCPhrase(REBEL_HELLO_1); // "REBEL_HELLO_1" emit "YEHAT_REBEL_VISITS" getContext 1 + "YEHAT_REBEL_VISITS" setContext
            break;                    // }
        case 1:                       // dup 1 eq jgz {
            NPCPhrase(REBEL_HELLO_2); // "REBEL_HELLO_2" emit "YEHAT_REBEL_VISITS" getContext 1 + "YEHAT_REBEL_VISITS" setContext
            break;                    // }
        case 2:                       // dup 2 eq jgz {
            NPCPhrase(REBEL_HELLO_3); // "REBEL_HELLO_3" emit "YEHAT_REBEL_VISITS" getContext 1 + "YEHAT_REBEL_VISITS" setContext
            break;                    // }
        case 3:                       // 3 eq jgz {
            NPCPhrase(REBEL_HELLO_4); // "REBEL_HELLO_4" emit
            --NumVisits;
            break; // }
        }
        SET_GAME_STATE(YEHAT_REBEL_VISITS, NumVisits); //

        Rebels((RESPONSE_REF)0); // "Rebels" goto
    }                            // }
} // getResponse goto exit }

static COUNT
uninit_yehat(void)
{
    return (0);
}

static void
post_yehat_enc(void)
{
    /* nothing defined so far */
} // getResponse goto exit }

LOCDATA *
init_rebel_yehat_comm(void)
{
    LOCDATA *retval;

    yehat_desc.init_encounter_func = Intro;
    yehat_desc.post_encounter_func = post_yehat_enc;
    yehat_desc.uninit_encounter_func = uninit_yehat;

    yehat_desc.AlienTextBaseline.x = SIS_SCREEN_WIDTH * 2 / 3;
    yehat_desc.AlienTextBaseline.y = 60;
    yehat_desc.AlienTextWidth = (SIS_TEXT_WIDTH - 16) * 2 / 3;

    /* use alternate "Rebels" track if available */ // jgz
    yehat_desc.AlienAltSongRes = REBEL_MUSIC;
    yehat_desc.AlienSongFlags |= LDASF_USE_ALTERNATE;

    setSegue(Segue_peace);
    retval = &yehat_desc;

    return (retval);
}
